// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebScanner.Models.Database;

namespace WebScanner.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20181213125527_AlterResponsesTable")]
    partial class AlterResponsesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("WebScanner.Models.HtmlOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Frequency");

                    b.Property<string>("SubjectOfQuestion");

                    b.Property<string>("TargetAddress");

                    b.HasKey("Id");

                    b.ToTable("HtmlOrders");
                });

            modelBuilder.Entity("WebScanner.Models.Response", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTime>("Date");

                    b.Property<int>("OrderId");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("WebScanner.Models.ServerOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Frequency");

                    b.Property<string>("Question");

                    b.Property<string>("TargetAddress");

                    b.HasKey("Id");

                    b.ToTable("ServerOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
